### ISSUE TITLE
[Vue warn]: Invalid key "require" in validation rules object for prop "value".

### ISSUE THREAD

**Issue by frzkhan** [trionfo1993/vue2-typeahead#10]
Really useful component, great job

however i get these warnings in console, basically for every props, because you have written `require` instead of `required` in it
`[Vue warn]: Invalid key "require" in validation rules object for prop "value".`
```
value: {
        require: true,
        type: String
      },
```
after this you might also see that the `value` prop can not be set as `required` because its not passed in

**Comment by trionfo1993** [comment]
Thanks
