### ISSUE TITLE
Missing required prop: "getResponse"

### ISSUE THREAD

**Issue by joemsak** [trionfo1993/vue2-typeahead#11]
package.json
```
{
  "dependencies": {
    "@rails/webpacker": "^3.2.1",
    "luxon": "^0.4.0",
    "moment": "^2.20.1",
    "vue": "^2.5.13",
    "vue-datetime": "^1.0.0-beta.2",
    "vue-dragula": "^1.3.1",
    "vue-loader": "^13.7.0",
    "vue-template-compiler": "^2.5.13",
    "vue-turbolinks": "^2.0.1",
    "vue2-typeahead": "^1.0.17",
    "weekstart": "^1.0.0"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.11.1"
  }
}
```

When I implement the component as documented, I get this warning from vue that the getResponse prop is missing. It also warns me that the value prop is missing, though this is not mentioned in the documentation as a required prop.

When I start typing it attempts a search and hits the network but the component itself complains that `this.getResponse` is not a function

HTML
```
<type-ahead
  :getResponse="getResponse"
  src="<URL-OMITTED>"
></type-ahead>
```

JS
```
import TypeAhead from 'vue2-typeahead';

// unrelated code has been omitted

new Vue({
    methods: {
      getResponse (response) {
        return response;
      },
    },

    components: {
      TypeAhead,
    },
});
```

(using rails 5.1 with webpacker)

**Comment by trionfo1993** [comment]
value or v-model is required，
i haven't try to run this on ruby, can you provide the webpack.conf for me?

**Comment by joemsak** [comment]
You might want to update the doc here to indicate that value or v-model are required
https://github.com/trionfo1993/vue2-typeahead#sample

Here is the webpack config that comes generated by rails' helpers, I haven't touched it myself

https://github.com/Iridescent-CM/technovation-app/tree/full-rpe-with-judges/config/webpack
https://github.com/Iridescent-CM/technovation-app/blob/full-rpe-with-judges/config/webpacker.yml
