### ISSUE TITLE
Making src property optional

### ISSUE THREAD

**Issue by ashitvora** [trionfo1993/vue2-typeahead#12]
I have all the data needed for typeahead. Is there a way to make src property options?
Having following properties would make the component a lot easier to use...
1. data (array of available attributes)
2. property to display when an item is selected from an array of Objects.

**Comment by andrewpeters9** [comment]
https://github.com/andrewpeters9/vue2-typeahead

Check out my fork, it was fairly rushed though, so be careful. @trionfo1993 let me know if you're open to allowing this functionality and I'll clean up my code and create a PR.

**Comment by trionfo1993** [comment]
Sure

发自我的 iPhone

在 2018年2月16日，下午3:30，andrewpeters9 <notifications@github.com<mailto:notifications@github.com>> 写道：


https://github.com/andrewpeters9/vue2-typeahead

Check out my fork, it was fairly rushed though, so be careful. @trionfo1993<https://github.com/trionfo1993> let me know if you're open to allowing this functionality and I'll clean up my code and create a PR.
