### ISSUE TITLE
 Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by raajshekhar** [trionfo1993/vue2-typeahead#13]
I am using the typeahead but not getting the ouput it throws an error.
I have changed in getResponse func because i want to show the suggestions are names
please help me
--------TypeAhead.vue?be70:185 Uncaught (in promise) 
TypeError: Cannot read property 'slice' of undefined
    at eval (TypeAhead.vue?be70:185)
    at <anonymous>-----

Code:
<TypeAhead
      v-model="data"
      :classes="classes"
      :placeholder="placeholder"
      src="https://jsonplaceholder.typicode.com/users?keyword=:keyword"
      :getResponse="getResponse"
      :selectFirst="selectFirst"
      :limit="parseInt(limit)"
      :queryParamName="queryParamName"
      :minChars="parseInt(minChars)"
      :delayTime="parseInt(delayTime)"
      :onHit="onHit"
      :highlighting="highlighting"
      :render="render"
      :fetch="fetch"
    ></TypeAhead>

 getResponse: function (response) {
        console.log(response.data);
        return response.data.id;
      },
      onHit: function (item, vue, index) {
        vue.query = item
      },
      highlighting: function (item, vue) {
        return item.toString().replace(vue.query, `<b>${vue.query}</b>`)
      },
      render: function (items, vue) {
        // 将搜索内容作为list的第一个
        let newItem = [vue.query, ...items]
        return newItem
      },
      fetch: function (url) {
        return axios.get(url)
      }

**Comment by nicosli** [comment]
I have de same problem

**Comment by NathanielInman** [comment]
I resolved the issue by ensuring i was returning an array of strings as the result of `getResponse`.
```
getResponse(res){
  return res.data.map(option=> option.name);
}
```

**Comment by divyashravanthi** [comment]
+1

**Comment by jbcanas** [comment]
@NathanielInman was correct, just make sure your **getResponse** returns an array.
I encountered this error when my request to my API returns an object instead of an array.
