### ISSUE TITLE
Problem with model in v-for table

### ISSUE THREAD

**Issue by 50l3r** [trionfo1993/vue2-typeahead#15]
Hi guys,

I have this problem:

[![https://gyazo.com/6174c28090e7eee27900f9e15f91d292](https://i.gyazo.com/6174c28090e7eee27900f9e15f91d292.gif)](https://gyazo.com/6174c28090e7eee27900f9e15f91d292)

All this fields should be filled but only can fill the firts:

This is my code:

	<template>
		<div class="table-responsive">
			<table class="table color-table inverse-table table-hover table-striped">
				<thead>
					<tr><th>Concepto</th></tr>
				</thead>
				<tbody>
					<tr v-for="(item,index) in conceptos">
						<td :id="'conceptos_descripcion_'+ index">
							<typeahead :src="source_products(index)" :getResponse="type_products_response" :onHit="type_products_hit" placeholder="Introduce la descripción del producto" v-model="conceptos[index].Description" :highlighting="highlighting"></typeahead>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</template>

	<script>
		import {paths, datepicker} from '../../../config/config'
		import typeahead from 'vue2-typeahead'

		export default {
			name: 'demo',
			components: {
				'typeahead': typeahead,
			},
			data() {
				return {
					typeahead: {
						search_business: "",
						business_items: [],
						conceptos: [],
					},
					conceptos: [
						{
							Description: "",
							Quantity: 1,
							Price: 0,
							Product: 0,
							Discount: 0
						}
					],
				}
			},
			created: async function(){
				var self = this

				var data = await this.$root.get('facturas', 4);

				if(data){
					this.conceptos = []

					data.Conceptos.forEach((concepto) => {
						self.conceptos.push({
							Description: concepto.Concepto,
							Quantity: concepto.Cantidad,
							Price: concepto.Precio,
							Product: concepto.Producto,
							Discount: concepto.Descuento
						})
					})
				}else{
					alert('pagina-no-encontrada')
				}
			},
			methods:{
				source_products(index){
					var filter = this.$root.filter('productos', this.conceptos[index].Description);
					return paths.api + '/app/productos?limit=5&filters='+JSON.stringify(filter)
				},
				type_products_response: function (response) {
					var newitems = [];
					this.typeahead.products_items = [];

					response.data.data.forEach((item) => {
						newitems.push(item.ProductoNombre)
						this.typeahead.products_items.push(item);
					});
					return newitems
				},
				type_products_hit: function (item, vue, index) {
					this.conceptos[this.concepto_focus].Description = this.typeahead.products_items[index].ProductoNombre;
					this.conceptos[this.concepto_focus].Product = this.typeahead.products_items[index]._EntityId;
					this.conceptos[this.concepto_focus].Price = this.typeahead.products_items[index].ProductoPrecio;

					if(this.conceptos[this.concepto_focus].Quantity==0){
						this.conceptos[this.concepto_focus].Quantity = 1;
					}

					vue.query = item
				},
				highlighting: function (item, vue) {
					var path = "";
					this.typeahead.products_items.forEach((producto) => {
						if(producto.ProductoNombre==item){
							path = paths.media+'/productos/ProductoImagen/'+producto.ProductoImagen
						}
					})

					if(path){
						return "<img class='m-r-5' src='"+path+"' height='18px'>"+item.replace(vue.query, '<b>'+vue.query+'</b>')
					}else{
						return item.replace(vue.query, '<b>'+vue.query+'</b>')
					}
				},
			}
		}
	</script>

	<style>

	</style>

**Comment by 50l3r** [comment]
i investigated and found that prop value is filled but not rendered in input value:

[![https://gyazo.com/d853ca02825cc3aca67c3e610a657aa4](https://i.gyazo.com/d853ca02825cc3aca67c3e610a657aa4.png)](https://gyazo.com/d853ca02825cc3aca67c3e610a657aa4)

**Comment by asadyounis** [comment]
me too, i have this problem, but i didn't fixed it yet.

**Comment by vincent-lu** [comment]
Adding this line at the end of `mounted()` seems to fix the problem for me:
```
this.query = this.value;
```

**Comment by 50l3r** [comment]
Problem solved :)

**Comment by vincent-lu** [comment]
@trionfo1993 Maybe make this update so everyone can get the fix? Thanks.

**Comment by trionfo1993** [comment]
Of course

发自我的 iPhone

在 2018年6月14日，下午3:37，Vincent Lu <notifications@github.com<mailto:notifications@github.com>> 写道：


@trionfo1993<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftrionfo1993&data=02%7C01%7C%7Cbc15adb17690481e8c8c08d5d1c99ebf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636645586234823283&sdata=t1j0hZdv%2F1y8%2Bn6LUhhruPgLneYLgSanfvEFI6meObw%3D&reserved=0> Maybe make this update so everyone can get the fix? Thanks.
