### ISSUE TITLE
Doesn't seem to work with bootstrap 4

### ISSUE THREAD

**Issue by Rajan** [trionfo1993/vue2-typeahead#2]
Produces following output which is collapsed and hence hidden.

`<nav data-v-42809415="" role="navigation" class="collapse navbar-collapse"><div data-v-42809415="" class="input-group"><input data-v-42809415="" type="text" autocomplete="off" class="form-control"> <ul data-v-42809415="" role="menu" aria-labelledby="dropdownMenu" class="dropdown-menu-list dropdown-menu" style="display: none;"></ul> <!----></div></nav>`

**Comment by trionfo1993** [comment]
ok， i will check it

**Comment by oldskool73** [comment]
same thing's happening for me with Bootstrap3, when screen is < 786px wide `.collapse` class makes the whole component hidden.

**Comment by trionfo1993** [comment]
@oldskool73 My mistake，I am so sorry for copy additional element when coding，please use new version ，thanks
