### ISSUE TITLE
`Up` & `Down` don't pass `this` to `onHit`

### ISSUE THREAD

**Issue by oldskool73** [trionfo1993/vue2-typeahead#3]
Hi,

As the title says, the `up` and `down` methods don't pass the `this`/`vue` instance to the `onHit` function in the same way that the `hit` method does. 

So if you set your own `onHit` property, as shown in the example ... 

```
onHit: function (item, vue) {
        vue.query = item
      },
```

you get errors about `Cannot set property 'query' of undefined`

**Comment by trionfo1993** [comment]
Thanks
