### ISSUE TITLE
Disable first result of query

### ISSUE THREAD

**Issue by DaAwesomeP** [trionfo1993/vue2-typeahead#5]
Thank you for all your work on this component! The abstracted, configurable methods make it very flexible. How can I disable the first result of each query that simple repeats the query? My form only accepts the exact results and does not allow for created/unlisted items.

**Comment by trionfo1993** [comment]
try add render function to the component ?
remove vue.query like this
```
      render: function (items, vue) {
        return items
      },
````

**Comment by DaAwesomeP** [comment]
Thank you! I copied that method in and simply didn't catch that.
