### ISSUE TITLE
Render template

### ISSUE THREAD

**Issue by mesutgok** [trionfo1993/vue2-typeahead#6]
Hi,
Component is simple and clean 👍 
Render template don't send to object. [{description : 'bla bla', id:0}, {description : 'bla bla 2', id:2}]
I will make another ajax request when selected.  (id sending)

**Comment by trionfo1993** [comment]
Sorry， but i can't understand what you want to tell me

**Comment by mesutgok** [comment]
items data object not string array so example;

items = ['istanbul', 'ankara'] ⛔️  

my items;  items = [{id:0, city : 'istanbul'}, {id:2, city : 'ankara'}] 👍   

object property id send another ajax request cityDetail send but on hit how do get id ?

**Comment by trionfo1993** [comment]
Emmmm, my mistake, i don't keep the cache of response, in new version，you can get it in component's attribute, **data**, try 
```

onHit(item, vue) {
    let current = vue.current
    let selectedItem = vue.data[current]
    let id = selectedItem.id
}

  
 ```

**Comment by trionfo1993** [comment]
By the way, npm publish is hard in china

**Comment by mesutgok** [comment]
ok thanks for reply. i will try
